# Generated by Django 5.1.6 on 2025-03-04 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0002_user_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='img',
            new_name='Profile_Images',
        ),
    ]
